title: Manuele Albano – Technical Writer
description: Technical writing portfolio

theme: just-the-docs

url: https://manualbano-lgtm.github.io

logo: /assets/images/profile.png

aux_links:
  Portfolio on GitHub: https://github.com/manualbano-lgtm
