title: Manuele Albano – Technical Writer
description: Technical writing portfolio

remote_theme: just-the-docs/just-the-docs
logo: /assets/images/profile.png

url: https://manualbano-lgtm.github.io

aux_links:
  GitHub: https://github.com/yourusername

plugins:
  - jekyll-remote-theme
